### PR TITLE
Various improvements in netty usage

### PR DESCRIPTION
**Pull request by normanmaurer**

### CODE REVIEW

**Comment by tjake** [comment]
Thanks, could you squash and include the JIRA in the commit?

**Comment by tjake** [comment]
Actually just linking this to the apache Jira is enough

**Comment by normanmaurer** [comment]
@tjake done!

**Comment by JeremiahDJordan** [comment]
The ASF auto closing stuff didn't close this for some reason, can you close it @normanmaurer? Thanks!

**Pull request closed without merging**
