### PR TITLE
add :stem: latexmath to page with equations

### PR DESCRIPTION
**Pull request by polandll**
Thanks for sending a pull request! Here are some tips if you're new here:
 
 * Ensure you have added or run the [appropriate tests](https://cassandra.apache.org/_/development/testing.html) for your PR.
 * Be sure to keep the PR description updated to reflect all changes.
 * Write your PR title to summarize what this PR proposes.
 * If possible, provide a concise example to reproduce the issue for a faster review.
 * Read our [contributor guidelines](https://cassandra.apache.org/_/development/index.html)
 * If you're making a documentation change, see our [guide to documentation contribution](https://cassandra.apache.org/_/development/documentation.html)
 
Commit messages should follow the following format:

```
<One sentence description, usually Jira title or CHANGES.txt summary>

<Optional lengthier description (context on patch)>

patch by <Authors>; reviewed by <Reviewers> for CASSANDRA-#####

Co-authored-by: Name1 <email1>
Co-authored-by: Name2 <email2>

```

The [Cassandra Jira](https://issues.apache.org/jira/projects/CASSANDRA/issues/)

### CODE REVIEW

**Comment by polandll** [comment]
formula-fix-cass-build

**Review by ErickRamirezAU — APPROVED** [review]

**Comment by ErickRamirezAU** [comment]
Note that I've reworded the commit message to comply with the required format. Cheers! 🍻

**Comment by polandll** [comment]
Note that I've reworded the commit message to comply with the required format.

This PR will need to be merged to 3.11, 4.0, 4.1 and trunk branches. Cheers! 🍻

**Comment by polandll** [comment]
Committed and closed

**Pull request closed without merging**
