### PR TITLE
remove redundant paragraphs

### PR DESCRIPTION
**Pull request by xialeistudio**
Remove redundant paragraphs at **Cassandra/Architecture/Storage engine**

### CODE REVIEW

**Comment by smiklosovic** [comment]
@xialeistudio why do you think it is redundant?

**Comment by xialeistudio** [comment]
Because I found that the content of these two paragraphs is same.

**Comment by smiklosovic** [comment]
Can you show me the second paragraph? I just dont see it.

**Comment by xialeistudio** [comment]
OK, the following screenshot shows two paragraphs.

image

**Comment by polandll** [comment]
This is redundant in cassandra-4.1 and cassandra-4.0.

**Review by polandll — APPROVED** [review]
This is true, it is redundant in 4.1 and 4.0, but not present in trunk.

**Comment by xialeistudio** [comment]
Thank you~

**Comment by smiklosovic** [comment]
I think we can just close this as this issue is not present in the documentation for trunk anymore. We could spend years fixing all documentation for previous versions ...

**Pull request closed without merging**
