### PR TITLE
sasi: AND optimizations

### PR DESCRIPTION
**Pull request by iksaif**
See CASSANDRA-12915

when op is AND:
- do not use indexes that return way more results that the others
- do not use more indexes if one of them returns no results
- try to use something smarter to get the primary index (which is
  important because it limits the searches done on other indexes)

Cosmetic changes such as changing logger.debug() to logger.trace() will be done later, I'd like a first opinion on the concept.

### CODE REVIEW

**Comment by blerer** [comment]
Is there a JIRA ticket associated to your patch?

**Comment by blerer** [comment]
I guess it is CASSANDRA-12915. Could you mark it as patch available?

**Comment by iksaif** [comment]
Done, I'm not yet very familiar with the workflow.

**Comment by blerer** [comment]
Thanks. :-)
People are usually tracking the JIRA tickets and not the pull requests. So it is best to keep it in sync with your developments.

**Pull request closed without merging**
