### PR TITLE
CASSANDRA-14432: clean up build artifacts in docs container

### PR DESCRIPTION
**Pull request by jameslamb**
Small PR to cut out some unnecessary stuff in the docs container. Please see the PR description in [CASSANDRA-14432](https://issues.apache.org/jira/browse/CASSANDRA-14432).

### CODE REVIEW

**Comment by joaquincasares** [comment]
Thanks for cleaning those items up.

+1 from me. Committers, do please merge.

**Comment by jameslamb** [comment]
I'm confused. This PR is still open but it looks like this got closed in: https://issues.apache.org/jira/browse/CASSANDRA-14432

What am I missing?

**Comment by jameslamb** [comment]
I do see this commit: https://github.com/apache/cassandra/commit/f2ee3db6537005f9ae8582cecd8e29df29ac30d5

can this PR be closed?

**Comment by jasobrown** [comment]
Yes, you need to close it as no one else has privs to (and we do not add github-specific text to the commit messages in the cassandra ASF repo)

**Comment by jameslamb** [comment]
@jasobrown ok cool, makes sense! Hadn't seen a project that did that before.

Thank you very much!

**Pull request closed without merging**
