### PR TITLE
CASSANDRA-16987 Make cqlsh shell script ready for Python 3.10+

### PR DESCRIPTION
**Pull request by bowensong**
This fixes [CASSANDRA-16987](https://issues.apache.org/jira/browse/CASSANDRA-16987).

Please let me know if anything isn't quiet right. Keep in mind that this is my first attempt to contribute to the Cassandra project. I'm doing this quick fix to get myself familiarise with the process before I work on some more complex ones.

### CODE REVIEW

**Review by azotcsit — APPROVED** [review]
The fix seems to be working fine:
```
2.6 non-supported
2.7 supported
2.10 non-supported
3.1 non-supported
3.5 non-supported
3.6 supported
3.9 supported
3.10 supported
```

LGTM!

**Comment by jeffwidman** [comment]
@bowensong it looks like this was merged already, should this PR be closed?

**Comment by bowensong** [comment]
> @bowensong it looks like this was merged already, should this PR be closed?

Yes. Please feel free to close this PR.

**Comment by jeffwidman** [comment]
I can't, I'm just a drive-by user who was searching the PR list for "python" to see what changes were in-flight for cqlsh... 

Only the author (you) or maintainers can close this.

**Comment by bowensong** [comment]
> I can't, I'm just a drive-by user who was searching the PR list for "python" to see what changes were in-flight for cqlsh...
> 
> Only the author (you) or maintainers can close this.

Sorry, I mistaken you as one of the maintainers. Let me close it.

**Pull request closed without merging**
