### PR TITLE
CASSANDRA-12541, CASSANDRA-12542, CASSANDRA-12543 and CASSANDRA-12545

### PR DESCRIPTION
**Pull request by deshpamit**

### CODE REVIEW

**Comment by doanduyhai** [comment]
Can you give some description of the issue ?

**Comment by deshpamit** [comment]
HP Fortify Analysis flagged Portability Flaw: Locale Dependent Comparison
https://issues.apache.org/jira/browse/CASSANDRA-12541 same issue for all defects

**Comment by edwardcapriolo** [comment]
+1

**Comment by jeffjirsa** [comment]
@deshpamit - Thanks so much for your patch. Two points:

1) The project uses JIRA for patches and issue tracking, not github issues / pull requests. We'll try to get patches wherever they arrive, but for consistency, posting on the JIRA is more likely to be seen.
2) You're missing a close paren here: https://github.com/apache/cassandra/pull/76/files#diff-8d033ba4918a0c6a3781e675678f3ac3R196

I encourage you to review http://cassandra.apache.org/doc/latest/development/patches.html as well - we'll do our best to accept patches as quickly as we can, but if they match the expected format, it's much easier for committers to review and commit.

**Pull request closed without merging**
