### PR TITLE
DOC - Fix typo in CQL Data Definition page

### PR DESCRIPTION
**Pull request by utkarsh-agrawal-jm**

### CODE REVIEW

**Review by Claudenw — APPROVED** [review]
This is a correction to a typo.  How much review do we need?

**Comment by ErickRamirezAU** [comment]
@smiklosovic thanks for the ping! I'm sorry I didn't see it until now, got buried in my emails. 🙏

@utkarsh-agrawal-jm thanks for logging [CASSANDRA-17742](https://issues.apache.org/jira/browse/CASSANDRA-17742). Reviewing it now. 🍻

**Review by ErickRamirezAU — CHANGES_REQUESTED** [review]
@utkarsh-agrawal-jm we maintain 4 versions of the Docs on the website so this needs to go into 4 branches, not just `trunk`. Details in the ticket -- let's chat there as required. 🍻

**Comment by ErickRamirezAU** [comment]
> This is a correction to a typo. How much review do we need?

@Claudenw thanks for the feedback. It isn't so much a "technical review" but an opportunity to mentor new contributors on the process/logistics of contributing. 🙂

**Comment by smiklosovic** [comment]
thank you, this work will be included in https://github.com/apache/cassandra/pull/2062

**Pull request closed without merging**
