### PR TITLE
CASSANDRA-16384 test case AuditLoggerTest fail on aarch64 platform

### PR DESCRIPTION
**Pull request by zhaorenhai**
CASSANDRA-16384 test case AuditLoggerTest fail on aarch64 platform
CASSANDRA-16392 Unable to load the library netty_tcnative_linux_aarch_64

Upgrade chronicle*jar and netty-tcnative*jar to fix above 2 issues on aarch64

### CODE REVIEW

**Comment by michaelsembwever** [comment]
The license files under `lib/licenses/` also need to be renamed (and checked for updates)

**Comment by michaelsembwever** [comment]
it's looking much better now.

can we please…
- rename `lib/licenses/chronicle-core-2.20.126-SNAPSHOT.txt` to `lib/licenses/chronicle-core-2.20.126.txt`
- rename `lib/licenses/netty-4.1.58.txt` to `lib/licenses/netty-all-4.1.58.txt`
- rename `lib/licenses/netty-tcnative-2.0.36.txt` to `lib/licenses/netty-tcnative-boringssl-static-2.0.36.txt`

 (even though these faults existed before this PR, if we're going to touch them let's correct them to the standard)

**Comment by zhaorenhai** [comment]
Hello, mck, now files have been renamed as your request.

**Comment by zhaorenhai** [comment]
Hello, mck, if no issue, could you help to merge this?

**Review by michaelsembwever — APPROVED** [review]

**Pull request closed without merging**
