### PR TITLE
[CASSANDRA-18340] Upgrade snakeyaml from 1.26 to 2.0

### PR DESCRIPTION
**Pull request by bipinprasad**
CVE's are listed here https://mvnrepository.com/artifact/org.yaml/snakeyaml/1.26

Constructor signataure has changed in the snakeyaml 2.0. Apache Storm project has an example project "storm-cassandra".
To fully implement snakeyaml 2,0 in Storm, it needs a Cassandra build with smakeyaml 2.0 as well.

<Optional lengthier description (context on patch)>

patch by [bipinprasad@apache.org](mailto:bipinprasad@apache.org); reviewed by for CASSANDRA-#####

Co-authored-by: Name1
Co-authored-by: Name2

The [Cassandra Jira](https://issues.apache.org/jira/browse/CASSANDRA-18340)

```
<One sentence description, usually Jira title or CHANGES.txt summary>

<Optional lengthier description (context on patch)>

patch by <Authors>; reviewed by <Reviewers> for CASSANDRA-#####

Co-authored-by: Name1 <email1>
Co-authored-by: Name2 <email2>

```

The [Cassandra Jira](https://issues.apache.org/jira/projects/CASSANDRA/CASSANDRA-18340/)

### CODE REVIEW

**Comment by bipinprasad** [comment]
Same changes as in the closed PR https://github.com/apache/cassandra/pull/2224

**Comment by c3ivodujmovic** [comment]
@bipinprasad @smiklosovic any updates on merging this to 3.11?

**Comment by driftx** [comment]
CASSSANDRA-18340 is closed, this requires a new jira.

**Comment by ddezoysa** [comment]
Can someone please share in which release this snakeyaml upgrade to 2.0 fix supposed to be released?

**Comment by driftx** [comment]
None without a jira ticket.

**Comment by ddezoysa** [comment]
@driftx Raised [CASSANDRA-18672](https://issues.apache.org/jira/browse/CASSANDRA-18672)
Please do the needful.

**Pull request closed without merging**
