### PR TITLE
CASSANDRA-17663 Ensure FileStreamTask cannot compromise shared channel proxy for system table when interrupted

### PR DESCRIPTION
**Pull request by maedhroz**

### CODE REVIEW

**Comment by maedhroz** [comment]
https://app.circleci.com/pipelines/github/maedhroz/cassandra?branch=CASSANDRA-17663-4.0&filter=all

**Comment by maedhroz** [comment]
J11 tests hit [CASSANDRA-17139](https://issues.apache.org/jira/browse/CASSANDRA-17139)

**Comment by maedhroz** [comment]
J8 tests hit [CASSANDRA-17213](https://issues.apache.org/jira/browse/CASSANDRA-17213)

**Comment by maedhroz** [comment]
Failures in `TestCQLNodes3RF3_Upgrade_current_3_11_x_To_indev_4_0_x` look preexisting...

https://butler.cassandra.apache.org/#/ci/upstream/compare/Cassandra-4.0/cassandra-4.0

**Review by jonmeredith — APPROVED** [review]

**Comment by maedhroz** [comment]
Committed in a00d8fd5ba9d73a377d1a11e6f540c56d66e9c8f

**Pull request closed without merging**
