### PR TITLE
CASSANDRA-18086: Fix wait time returned to be in nanoseconds

### PR DESCRIPTION
**Pull request by marianne-manaog**
A bug fix for 'wait' time to be in nanoseconds for consistency instead of microseconds.

patch by @marianne-manaog, although fix suggested by @belliottsmith;

The [Cassandra Jira](https://issues.apache.org/jira/browse/CASSANDRA-18086)

### CODE REVIEW

**Review by aweisberg — CHANGES_REQUESTED** [review]
Can you add a unit test to `ContentionStrategyTest` that checks that `computeWaitUntilForContention` is producing values in the range we want?

A better fix is probably to only use microseconds in configuration where it makes expressing the configuration easier and convert to nanoseconds immediately upon reading the configuration. @belliottsmith  WDYT?

At a higher level a [`Duration`](https://github.com/airlift/units/blob/c25cb5704978c48f8ce966d0c06447e351cab609/src/main/java/io/airlift/units/Duration.java) would be safer. It works as both a return value and a parameter unlike `TimeUnit` which doesn't pair well with a value.

Or we can keep going with somewhat ambiguous types and just be careful about naming and converting things to nanoseconds as soon as possible.

**Comment by belliottsmith** [comment]
Yes, we could definitely convert to nanos earlier and always use nanos. Perhaps we can do that in a follow-up patch.

**Comment by belliottsmith** [comment]
Marianne, I think you intended to merge the 18097 PR in here, but it seems to have merged "cleanly" meaning none of the commits were adopted. Not sure what happened there.

**Comment by marianne-manaog** [comment]
Thanks for your comment, @belliottsmith. I have updated this branch and PR to reflect all related changes required for review.

> Marianne, I think you intended to merge the 18097 PR in here, but it seems to have merged "cleanly" meaning none of the commits were adopted. Not sure what happened there.

**Review by belliottsmith — APPROVED** [review]
Thanks!

**Comment by marianne-manaog** [comment]
Thanks for your comment, @aweisberg. @mfleming kindly added the required tests in [this commit](8ec9d77de6492189fdce92d4b09e9104c6626fae).

> Can you add a unit test to `ContentionStrategyTest` that checks that `computeWaitUntilForContention` is producing values in the range we want?
> 
> A better fix is probably to only use microseconds in configuration where it makes expressing the configuration easier and convert to nanoseconds immediately upon reading the configuration. @belliottsmith WDYT?
> 
> At a higher level a [`Duration`](https://github.com/airlift/units/blob/c25cb5704978c48f8ce966d0c06447e351cab609/src/main/java/io/airlift/units/Duration.java) would be safer. It works as both a return value and a parameter unlike `TimeUnit` which doesn't pair well with a value.
> 
> Or we can keep going with somewhat ambiguous types and just be careful about naming and converting things to nanoseconds as soon as possible.

**Comment by aweisberg** [comment]
Committed as [f0ad7eadbeb3208e08a9339881931222fdab253b](https://github.com/apache/cassandra/commit/f0ad7eadbeb3208e08a9339881931222fdab253b)

**Pull request closed without merging**
