### PR TITLE
CASSANDRA-15321 replace SNAPSHOT dependencies with STABLE

### PR DESCRIPTION
**Pull request by velo**
Hi peeps,

I just noticed that for cassandra 4.0-alpha1, the `cassandra-all` has a dependency to `chronicle-core` version `1.16.3-SNAPSHOT`.

http://repo1.maven.org/maven2/org/apache/cassandra/cassandra-all/4.0-alpha1/cassandra-all-4.0-alpha1.pom

Snapshots versions are not available on maven central, meaning `cassandra-all` can't be used as dependency for maven projects as is

### CODE REVIEW

**Comment by velo** [comment]
I also noticed cassandra-driver being SNAPSHOT and moved to use the release. And, that `carrotsearch` was missing from the dependency list. Added.

**Comment by michaelsembwever** [comment]
build failure with the driver version change. looking into it…

**Comment by velo** [comment]
@michaelsembwever  where is the build being executed? Can I see the error?

**Comment by michaelsembwever** [comment]
> where is the build being executed? Can I see the error?

@velo if you do `ant antifacts`

**Comment by michaelsembwever** [comment]
> build failure with the driver version change. looking into it…

if you undo the java-driver change, will maven builds using `cassandra-all` work again @velo ?

(i don't believe the name of the jar files themselves impact the maven declared dependencies. the java-driver used is a problem, it contains a version and code that is not found anywhere on the java-driver github repository, but i believe this can be fixed separately and is not part of your breakage here.)

**Comment by velo** [comment]
> if you undo the java-driver change, will maven builds using `cassandra-all` work again @velo ?

Yeah, I think that would be good enough for me.


BTW, replacing `/lib` folder with https://ant.apache.org/ivy/ would prevent this problem (and the cassandra driver one) from ever happening again.

**Pull request closed without merging**
