### PR TITLE
[wip] CASSANDRA-10496

### PR DESCRIPTION
**Pull request by iksaif**
Done:
- --split-output kind of work when running nodetool compact
- Values with timestamps outside of the first window should be isolated
  and merged back to the correct sstable (which maybe quite costly for now as
  it involves re-writing huge sstables for single values)

TODO:
- Unit tests
- Fix remaining TODOs

### CODE REVIEW

**Comment by michaelsembwever** [comment]
@iksaif,
 continuing the conversation from [CASSANDRA-10496](https://issues.apache.org/jira/browse/CASSANDRA-10496).

> What do you mean by "changing locations isn't supported" ?

`switchCompactionLocation(..)` is a public method and can be called from other places, when rows need to now be written to a new sstable in a new location. That's why [here](https://github.com/thelastpickle/cassandra/commit/a34a72391bb2847b3bd6ed93b4306199ddf3a991#diff-19359d40a9c932efdebc62a067ed4390R40) i paired writers by their location, so if a location changes the writer can also change.

> > Marcus' original idea was to create only two sstables per TWCS window.
>
> Currently it will create up to "minThreshold" sstables …

I'm not too sure I get that. The code you referenced is about which bucket is up for compaction, not how many writers to use during a bucket's compaction.
Marcus' idea was to only create two sstables per bucket, one that contains all the rows that belong in the bucket, and another for old data that's been streamed in late. Therefore `SplittingTimeWindowCompactionWriter. writersByBounds` should be a fixed array of size 2. The splitting approach as describe in  `SplittingTimeWindowCompactionWriter`'s class apidoc: splitting in half, then half, down to 50Mb; is quite different to the original idea.

> > shouldn't the bucket be based of the maxTimestamp? see `getBuckets(..)` and `newestBucket(..)`
>
> getBuckets() currently use maxTimestamp, , which isn't available (currently) in the compaction task

@krummas ?

> Are you talking about sstables generated before this patch ?

Yes.

**Comment by iksaif** [comment]
* `switchCompactionLocation(..)`: go it, will update code
* `Marcus' idea was to only create two sstables per bucket`: ok, I missed that. I'll see what I can get done here. Also the docstring was wrong.
* `sstables generated before this patch`: I wanted to think about the upgrade strategy only when the other questions would have been answered. If this get shipped before 4.0 is released this could be a non-issue.

**Comment by eliaslevy** [comment]
I am curious about the status of this work.

**Comment by iksaif** [comment]
I likely won't have time to finish, and `unsafe_aggressive_sstable_expiration` is good enough for our usecase now.

**Pull request closed without merging**
