### PR TITLE
Update CircleCI readme to match generate.sh usage

### PR DESCRIPTION
**Pull request by dchenbecker**
Add note on using the "-a" flag to generate all files

Patch by Derek Chen-Becker <apache@chen-becker.org>

### CODE REVIEW

**Review by michaelsembwever — APPROVED** [review]

**Comment by michaelsembwever** [comment]
@ekaterinadimitrova2 , wanna check this? (i'm not familiar with the `-a` flag)

**Comment by dchenbecker** [comment]
The "-a" flag was added in b6678a002cfa00be2068d499c5b7ce9c515bbc4e, but the README wasn't updated at the time

**Comment by michaelsembwever** [comment]
it looks like this PR is superseded by https://github.com/apache/cassandra/compare/cassandra-3.0...ekaterinadimitrova2:cassandra:17912-3.0?expand=1#diff-bac3a4a2bbeacb51b8f29f5dffbadbfc89f5960f84c0656e6c94c3e1d83a3442R79-R88 and CASSANDRA-17912

**Comment by dchenbecker** [comment]
Indeed it is! Closing this one

**Pull request closed without merging**
