### PR TITLE
adds support IP resolve option in nodetool status

### PR DESCRIPTION
**Pull request by yaitskov**
It's related with jira ticket CASSANDRA-2238.

### CODE REVIEW

**Comment by iamaleksey** [comment]
Please just attach a patch to the jira ticket in question, or post a link to your branch. This repo is a mirror, it cannot accept pull requests (so close this one, since we can't).

**Comment by yaitskov** [comment]
I did https://issues.apache.org/jira/browse/CASSANDRA-2238.

**Comment by JeremiahDJordan** [comment]
This repo is a mirror, it cannot accept pull requests. Please close this pull request as you have already  posted the patch to a JIRA ticket.

**Comment by jfarrell** [comment]
Requested to close all open pull requests by Cassandra PMC

**Pull request closed without merging**
