### PR TITLE
CASSANDRA-19197-trunk: Fix the correspondingMessagingVersion of SSTable format and improve TTL overflow tests coverage

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
(j11) https://app.circleci.com/pipelines/github/jacek-lewandowski/cassandra/1178/workflows/121faa16-9077-4ce6-9348-605be3fe7179

(j17) https://app.circleci.com/pipelines/github/jacek-lewandowski/cassandra/1178/workflows/fafc785d-0e94-4436-ad29-54607c18a5f6

**Comment by bereng** [comment]
Known flakies. The only one worth mentioning is https://app.circleci.com/pipelines/github/jacek-lewandowski/cassandra/1178/workflows/121faa16-9077-4ce6-9348-605be3fe7179/jobs/56885/tests which I haven't found in Jira. But being MVs and not seeing how it could be related to this ticket I'd say it's unrelated. I'd open a new ticket for it. Wdyt?

**Comment by jacek-lewandowski** [comment]
(j11) tries tests: https://app.circleci.com/pipelines/github/jacek-lewandowski/cassandra/1178/workflows/cda3ec8b-6e72-4ac7-b143-281976142cad

**Comment by jacek-lewandowski** [comment]
> Known flakies. The only one worth mentioning is https://app.circleci.com/pipelines/github/jacek-lewandowski/cassandra/1178/workflows/121faa16-9077-4ce6-9348-605be3fe7179/jobs/56885/tests which I haven't found in Jira. But being MVs and not seeing how it could be related to this ticket I'd say it's unrelated. I'd open a new ticket for it. Wdyt?

I don't know if it makes sense - it looks like some infra problem

**Comment by jacek-lewandowski** [comment]
tries tests 🟢

**Comment by jacek-lewandowski** [comment]
https://github.com/apache/cassandra/commit/2fc2be54caf4f1861cac8e93146ace03de5e1db6

**Pull request closed without merging**
