### PR TITLE
IDEA to mark unused imports as error

### PR DESCRIPTION
**Pull request by bereng**
Thanks for sending a pull request! Here are some tips if you're new here:
 
 * Ensure you have added or run the [appropriate tests](https://cassandra.apache.org/_/development/testing.html) for your PR.
 * Be sure to keep the PR description updated to reflect all changes.
 * Write your PR title to summarize what this PR proposes.
 * If possible, provide a concise example to reproduce the issue for a faster review.
 * Read our [contributor guidelines](https://cassandra.apache.org/_/development/index.html)
 * If you're making a documentation change, see our [guide to documentation contribution](https://cassandra.apache.org/_/development/documentation.html)
 
Commit messages should follow the following format:

```
<One sentence description, usually Jira title or CHANGES.txt summary>

<Optional lengthier description (context on patch)>

patch by <Authors>; reviewed by <Reviewers> for CASSANDRA-#####

Co-authored-by: Name1 <email1>
Co-authored-by: Name2 <email2>

```

The [Cassandra Jira](https://issues.apache.org/jira/projects/CASSANDRA/issues/)

### CODE REVIEW

**Comment by bereng** [comment]
CI builds [green](https://app.circleci.com/pipelines/github/bereng/cassandra/1067/workflows/1d005c8c-c1c4-4036-94c4-fe699cf4ec12/jobs/28738). No need to add junit imo.

**Comment by jacek-lewandowski** [comment]
+1, should such update be done also for Eclipse/Netbeans configuration (I don't know if anybody still uses that though)

**Comment by bereng** [comment]
^Sbdy with the IDE should test it :shrug:

**Comment by smiklosovic** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-18853?focusedCommentId=17766263&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17766263

**Comment by bereng** [comment]
Sorry not follwoing @smiklosovic, why that link to a comment in the ticket?

**Comment by smiklosovic** [comment]
@bereng because I clearly see that you are debating this PR but I got no response on the ticket so far.

**Comment by bereng** [comment]
I saw your comment and then your own response to which I agree so I didn't reply lol

**Review by Mmuzaf — APPROVED** [review]

**Pull request closed without merging**
