### PR TITLE
CASSANDRA-17465 add missing drop keyspace in test_unicode.py after test completion

### PR DESCRIPTION
**Pull request by bschoening**
added tearDownClass to call remove_db

### CODE REVIEW

**Review by jeffwidman — APPROVED** [review]

**Comment by bschoening** [comment]
any update on this PR?

**Comment by bschoening** [comment]
Note, test_cqlsh_completion.py and test_cqlsh_output.py do properly call remove_db in tearDownClass.  This test is simply missing it.

**Comment by jeffwidman** [comment]
Nudge on this PR @smiklosovic

**Comment by bschoening** [comment]
@smiklosovic I didn't see this merged, was it closed by mistake?

**Comment by smiklosovic** [comment]
I have not closed this. I wonder who did that. (or at least I dont remeber it?). Probably mistake, yes.

**Comment by smiklosovic** [comment]
@bschoening I do not have access to that branch anymore. Seems like "mysto" account do not exist anymore?

**Pull request closed without merging**
